services:
  # Next.js 애플리케이션 서비스
  nextjs-app:
    # 현재 디렉토리의 Dockerfile을 사용하여 이미지를 빌드합니다.
    build: .
    # 컨테이너 이름을 지정합니다.
    container_name: my-next-app
    # 네트워크를 통해 nginx가 이 이름으로 접근할 수 있습니다.
    hostname: nextjs-app
    # 재시작 정책을 설정합니다.
    restart: always
    # 'app-net' 네트워크에 연결합니다.
    networks:
      - app-net

  # Nginx 리버스 프록시 서비스
  nginx:
    # 공식 Nginx 이미지를 사용합니다.
    image: nginx:1.27-alpine-slim
    container_name: my-nginx-proxy
    # 호스트의 80번 포트를 컨테이너의 80번 포트와 연결합니다.
    ports:
      - "80:80"
    # 위에서 작성한 nginx.conf 파일을 컨테이너 내부로 복사(마운트)합니다.
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    # nextjs-app 서비스가 실행된 후에 nginx가 실행되도록 의존성을 설정합니다.
    depends_on:
      - nextjs-app
    restart: always
    networks:
      - app-net

# 서비스들이 사용할 브릿지 네트워크를 정의합니다.
networks:
  app-net:
    driver: bridge